### DISCUSSION TITLE
Disabling specific diagnostics after activating strict

### DISCUSSION THREAD

**Discussion by FrancescElies** [microsoft/pyright#4497] [Q&A] [answered]
Given these two files
```python
# mytest.py
def myfunc(a, b):
    print(a + b)
```

```python
# pyproject.toml
[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
include = ["."]
strict = ["."]
# strict disabled checks
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeStubs = false
```

I get the following errors 
```
mytest\strict on  master [?] via 🐍 v3.11.1
❯ pyright .
No configuration file found.
pyproject.toml file found at C:\s\mytest\strict.
Loading pyproject.toml file at C:\s\mytest\strict\pyproject.toml
Assuming Python version 3.11
Assuming Python platform Windows
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
stubPath C:\s\mytest\strict\typings is not a valid directory.
Searching for source files
Found 1 source file
pyright 1.1.290
C:\s\mytest\strict\mytest.py
  C:\s\mytest\strict\mytest.py:1:12 - error: Type of parameter "a" is unknown (reportUnknownParameterType)
  C:\s\mytest\strict\mytest.py:1:12 - error: Type annotation is missing for parameter "a" (reportMissingParameterType)
  C:\s\mytest\strict\mytest.py:1:15 - error: Type of parameter "b" is unknown (reportUnknownParameterType)
  C:\s\mytest\strict\mytest.py:1:15 - error: Type annotation is missing for parameter "b" (reportMissingParameterType)
  C:\s\mytest\strict\mytest.py:2:11 - error: Argument type is unknown
    Argument corresponds to parameter "values" in function "print" (reportUnknownArgumentType)
5 errors, 0 warnings, 0 informations
Completed in 0.596sec
```

Am I misusing something, I enabled strict but explicitely disabled those checks. What am I doing wrong?

**Comment by FrancescElies** [comment, marked as answer]
Same config bu instead of `strict = ["."]` using `typeCheckingMode = "strict"` produces the expected output without failures
```toml
[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md
include = ["."]
typeCheckingMode = "strict"
# strict disabled checks
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeStubs = false

```

**Reply by erictraut** [reply]
If you set the `typeCheckingMode` to "strict", it overrides all of the other configuration rules in the config file. If you don't want all of the strict-mode settings enabled, you can omit the `typeCheckingMode` (which defaults to "basic") and specify the desired severity level of each diagnostic check separately.

The config file mechanism was designed to accommodate incremental type checking. You can specify a "base" set of configuration rules that you would like to enable for your entire code base. You can then use the `strict` configuration setting to specify subsets of your code base (individual files or directories) where you would like to enable all strict-mode diagnostics.

For files that are being strictly checked, you can override individual diagnostic rules on a per-file basis using `# pyright` comments. For details, see [this documentation](https://github.com/microsoft/pyright/blob/main/docs/comments.md#file-level-type-controls).

**Reply by FrancescElies** [reply]
`typeCheckingMode = "strict"` works as expected the way you explained, that's not what surprised me.

What confused my was using `strict = ["."]` instead of `typeCheckingMode = "strict"` plus the same disabled checks did not have the same effect, are my expectations wrong in that case?
```toml
# pyproject.toml
[tool.pyright]
include = ["."]
# Instead of `typeCheckingMode = "strict"` I use here `include = ["."]`
strict = ["."]
# strict disabled checks
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeStubs = false
```
