### DISCUSSION TITLE
Need clarification about import resolution doc

### DISCUSSION THREAD

**Discussion by copdips** [microsoft/pyright#6444] [General]
Hello,

I would like to know if the doc [Import Resolution](https://github.com/microsoft/pyright/blob/main/docs/import-resolution.md#import-resolution) is for pyright in vscode, or also applies to standalone pyright ?

As the doc mentions some settings like: `python.venvPath`, `python.pythonPath` etc.

**Comment by erictraut** [comment]
Converting to discussion topic since this isn't a bug report or enhancement request.

**Reply by erictraut** [reply]
The import resolution section applies to both. If you are not using the language server, then the language server settings like `python.venvPath` and `python.pythonPath` don't apply.

**Reply by copdips** [reply]
Thx for the explanation.

From time to time, I have pyright libs not found issue during CICD process described [here](https://github.com/RobertCraigie/pyright-python/issues/213).

I'm running github action with default runner `ubuntu-latest` provided by github.
Should I also need to setup node/npm the github runner before running pyright ?

Currently, I do not setup anything about node/npm (maybe it is not related), but sometimes (really random) I got the above pyright libs not found errors.

**Reply by erictraut** [reply]
If node isn't installed in your CI/CD environment, pyright won't run at all, so that's probably not related to issues you're seeing with intermittent import resolution issues. 

Are you saying that the issue you're seeing is indeterminate — it happens on one run but not on the next? Do you see any patterns? 

I presume that you install your project's dependencies as part of the CI/CD script. Perhaps those installs are failing some of the time (e.g. due to a flaky network or issues with pypi)?

**Reply by copdips** [reply]
Node is always pre-installed by github default `ubuntu-latest` runner.
I install pyright just by `pip install pyright` without venv in CICD.
Yes, the issue really indeterminate.

Since I couldn't find a solution to the issue I opened on the author's github repo, I modified the `.pre-commit-config.yml` file to switch from system version to the repo version (example given below):

From a python interpreter (venv aware, perfect for local developement inside VSCode)

```yaml
# old .pre-commit-config.yml

- id: pyright
  name: pyright
  language: system
  entry: pyright
  types: [python]
 ```

To independant pyright 

```yaml
# new .pre-commit-config.yml

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.335
    hooks:
      - id: pyright
 ```

The downside of using the repo version is that pyright gets installed separately from the default python interpreter, so I need to tell it where it can find the python packages. While local developement uses venv, CICD does not. Unfortunately, there's no such option in Pyright to toggle between using a venv locally and not using one in CICD.

My current workaround involves the following pyright settings in `pyproject.toml`, which works well for both CICD and local developement with repo version of pyright installed by pre-commit (as shown above). I employ a turtle bash script to dynamically alter the `venv` settings value in `pyproject.toml` to match CICD runner's python interpreter path.

This is also the reason I initially sought this discussion. However, my fundamental problem is that I can't use Pyright installed via pip install during CI/CD due to an indeterminate issue.

```toml
# file pyproject.toml
[tool.pyright]
venvPath = "."
venv = ".venv"  # the value will be changed when it's run in a CICD process.
```
