### DISCUSSION TITLE
Exclude Jupyter notebooks completely from pyright

### DISCUSSION THREAD

**Discussion by medihack** [microsoft/pyright#7195] [Q&A]
In my Django project I use some Jupyter notebooks in a separate `notebooks` folder. I want to completely exclude those notebooks from being scanned by pyright. That is why I tried the following setting in my `pyproject.toml`:

```toml
[tool.pyright]
exclude = ["**/notebooks", "**/.ipynb*"]
ignore = ["**/migrations", "**/notebooks", "**/.ipynb*"]
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = true
```

Unfortunately, the VS Code extension (v1.1.349) does not respect this setting and still reports some `reportUndefinedVariable` errors (that are defined in some previous cells). How do I completely turn off pyright (VS Code extension) for specific folders or files?
