### DISCUSSION TITLE
How to ignore a module from checking as I do with with mypy?

### DISCUSSION THREAD

**Discussion by prokie** [microsoft/pyright#7320] [General]
Hi I am ignoring plotly from my mypy checks like this in my pyproject.toml

```toml
[[tool.mypy.overrides]]
module = ["plotly.*"]
ignore_missing_imports = true
```

how can I do the same for pyright? 
I want to get rid of all these warnings
![image](https://github.com/microsoft/pyright/assets/36114799/158a5ed2-397e-470a-9cdf-58001a506e0b)
