### DISCUSSION TITLE
How to use pyright with venv created by pdm?

### DISCUSSION THREAD

**Discussion by malik-n** [microsoft/pyright#9797] [General]
Pyright works correctly when using it in a [PDM script](https://pdm-project.org/latest/usage/scripts/) by defining the script in the pyproject.toml and setting pyright as dev dependency
``` toml
[dependency-groups]
dev = [
    "pyright",
]

[tool.pdm.scripts]
type-check = "pyright src"
```

When using Pyright by itself or as language server for [Helix](https://helix-editor.com/) the import statements cause errors. `(reportMissingImports)`

Trying to fix it in the pyproject.toml like this did not work:
``` toml
[tool.pyright]
venvPath = ".venv"
useLibraryCodeForTypes = true
```

The venv created by [PDM](https://github.com/pdm-project/pdm) is in the root of the project with the path `.venv` and the following directories and file inside: `bin  include  lib  pyvenv.cfg`

How do I setup the configuration correctly?

Propably related to #2767 and [pdm#804](https://github.com/pdm-project/pdm/issues/804)

**Comment by erictraut** [comment]
Converting to a discussion since this is a question, not a bug report.

**Comment by malik-n** [comment]
Found the solution here: https://notes.billmill.org/programming/python/pyright_use_virtualenv.html
``` toml
[tool.pyright]
venvPath='.'
venv=".venv"
exclude=['.venv']
```
