### ISSUE TITLE
reportGeneralTypeIssues reported via VS Code plugin but not pyright cli

### ISSUE THREAD

**Issue by NixBiks** [microsoft/pyright#2383]
**Describe the bug**

In my code I have VS Code extension reporting a type issue (correctly)

![a](https://user-images.githubusercontent.com/16841792/136176488-c1595e8d-4c91-4608-97e7-52effdfe79ee.png)

I'd like to catch this error via `pyright` command line tool. Here is my config from `pyproject.toml`

```toml
[tool.pyright]
exclude = [
    "**/__pycache__",
    "**/.venv",
    "**/generated",
]
venv= ".venv"
venvPath = "."
reportMissingImports = true
reportMissingTypeStubs = false
```

**Expected behavior**
I'd expect `pyright` to report the same error. I've tried explicitly setting `reportGeneralTypeIssues` in my config without any luck.

**VS Code extension or command-line**

I'm running pylance in VS Code and pyright 0.0.10 CLI.
