### ISSUE TITLE
Warning - file or directory -- does not exist

### ISSUE THREAD

**Issue by asears** [microsoft/pyright#2527]
**Describe the bug**

Getting a warning about file or directory -- does not exist.

```toml
[tool.pyright]
stubPath = ""  # typings by default shows warning
exclude = ["**/node_modules",
    "**/__pycache__"
]
ignore = ["source/","build/"]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.8.5"
pythonPlatform = "Linux"
```
```shell
Searching for source files
File or directory "C:\myprojectfolder\--" does not exist.
Found 21 source files
```
 
**VS Code extension or command-line**

Command line.  Pyright 0.0.11
