### ISSUE TITLE
`TypeGuard` and reassignment  not working as expected

### ISSUE THREAD

**Issue by vivax3794** [microsoft/pyright#2721]
**Describe the bug**
I have a union of `asyncio.Task[None] | Coroutine[Any, Any, None]` and I want to make it into just a `Task`, so I use the code
```py
import asyncio
from typing import Coroutine, Any

def add_task(self, task: asyncio.Task[None] | Coroutine[Any, Any, None]) -> None:
        if asyncio.iscoroutine(task):
            reveal_type(task)  # Coroutine[Any, Any, Any]
            task = asyncio.create_task(task)
            reveal_type(task)  # Task[None]

        reveal_type(task)  # Type of "task" is "Task[None] | Coroutine[Any, Any, None]"

        self._tasks.append(task)  # Argument of type "Task[None] | Coroutine[Any, Any, None]" cannot be assigned to parameter "__object" of type "Task[None]" in function "append"

```
but it pyright produces a result I was not expecting. 

**Expected behavior**
I would expect `task` to not still be a `union` after the if, as similar code using `isinstance` works correctly
```python
def foo(a: str | int) -> None:
    if isinstance(a, int):
        a = str(a)

    reveal_type(a)  # str
    b: str = a
```

**VS Code extension or command-line**
command-line
**version:** `pyright 1.1.196`
```toml
[tool.pyright]
typeCheckingMode = "strict"
reportPropertyTypeMismatch = "error"
reportUninitializedInstanceVariable = "error"
reportCallInDefaultInitializer = "error"
reportImplicitStringConcatenation = "error"
reportImportCycles = "none"
```
