### ISSUE TITLE
Pre-commit config is impossible

### ISSUE THREAD

**Issue by Goldziher** [microsoft/pyright#3902]
Hi there,

I am the author of [Starlite][https://github.com/starlite-api/starlite] and a user requested we support pyright better. I'm trying to set it up as part of our pre-commit configuration, which is crucial for our development, but this is really impossible.

I have this in my `.pre-commit-config.yaml`:

```yaml
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright@1.1.269"]
```

The issue is that I cannot specify any additional dependency in this way because the language is `node` and not python. This causes pyright to not find any of the dependencies in place.

I would like to ask for an official pre-commit-config that fixes this issue.

**Comment by Goldziher** [comment]
So, I got it to work doing this:

```yaml
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright -p .
        language: system
        pass_filenames: false
        types: [python]
```

* note the above is using poetry to execute pyright, and it requires adding a config file. 


BUT - for the above to work the user needs to have node installed. This means it will either not work in our CI (we use pre-commit in CI), or we will need to inject node there. Additionally, all contributors must have a compatible node version in place for this to work, and we have to add pyright into our dev dependencies.

I would suggest adding a pre-commit-config that uses a custom script, which makes sure everything is in place correctly.

Additionally - we cannot use the `autoupdate` functionality of pre-commit with the above, and `pre-commit-ci` will not be able to update it. So A solution in this repo is the best solution.
