### ISSUE TITLE
Support configuration from command line

### ISSUE THREAD

**Issue by brandonchinn178** [microsoft/pyright#4166]
**Is your feature request related to a problem? Please describe.**
If I have a short python script that I want to run pyright on, I don't want to have to set up a whole project to configure pyright.

**Describe the solution you'd like**
It would be nice to be able to do a quick
```bash
pyright --strict --option reportUnknownMemberType=false
```
but it would also be sufficient for my use-case to just have a general purpose
```bash
pyright --config '{"strict": ["*"], "reportUnknownMemberType": false}'
```

**Additional context**
Currently working around by writing out a `pyrightconfig.json` file in CI like
```yaml
- run: |
    cat > pyrightconfig.json <<EOF
    {
      "strict": ["*"],
      "reportUnknownMemberType": false
    }
    EOF

- uses: jakebailey/pyright-action@v1
```
but it would be nice to do something like
```yaml
- uses: jakebailey/pyright-action@v1
  with:
    config: |
      {
        "strict": ["*"],
        "reportUnknownMemberType": false
      }
```
