### ISSUE TITLE
`reportShadowedImports` regressed between 1.1.282 and 1.1.283

### ISSUE THREAD

**Issue by ottumm** [microsoft/pyright#4324]
This is for the command-line tool, using `reportShadowedImports = true` and the `--warnings` flag.

```toml
# pyproject.toml
[tool.pyright]
pythonVersion = "3.11"
include = ["scd"]
strict = ["scd"]

reportShadowedImports = true
```

```python
# src/copy.py
def copy(): ...
```

```python
# src/main.py
from .copy import copy
```

```
$ npx --yes pyright@1.1.283 --warnings
...
pyright 1.1.283
0 errors, 0 warnings, 0 informations 
Completed in 0.445sec
```

```
$ npx --yes pyright@1.1.282 --warnings
...
pyright 1.1.282
/Users/ottumm/danger/florist/scd/main.py
  /Users/ottumm/danger/florist/scd/main.py:2:1 - error: "/Users/ottumm/danger/florist/scd/copy.py" is overriding the stdlib module "copy" (reportShadowedImports)
1 error, 0 warnings, 0 informations 
Completed in 0.435sec
```
