### ISSUE TITLE
Cannot change type variables with using `type(self)` as a constructor

### ISSUE THREAD

**Issue by kyle-query** [microsoft/pyright#5412]
**Describe the bug**

```python
from typing import Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")

class Foo(Generic[T]):
    def __init__(self, t: T):
        self.t = t

    def swap0(self, u: U) -> "Foo[U]":
        return Foo(u) # ok
    
    def swap1(self, u: U) -> "Foo[U]":
        return type(self)(u) # <-- error
```

The error is:

```
Expression of type "Self@Foo[T@Foo]" cannot be assigned to return type "Foo[U@swap1]"
  "Foo[T@Foo]" is incompatible with "Foo[U@swap1]"
    TypeVar "T@Foo" is invariant
      Type "T@Foo" cannot be assigned to type "U@swap1"P
```

**Expected behavior**

I expected to be able to explicitly pass type variables like `type(self)[U](u)` which works fine when substituting `Foo` for `type(self)`, but pyright reports that `Foo[T@Foo]` is already specialized.

Perhaps when called as a constructor, `type(self)` should generate fresh type variables. This might be tricky because if there are phantom type variables, they cannot be inferred from the constructor call.

**VS Code extension or command-line**

You can reproduce this with pyright 1.1.316.

**Additional context**

I have the following configuration in pyproject.toml:

```toml
[tool.pyright]
pythonVersion                       = "3.10"
pythonPlatform                      = "Linux"
typeCheckingMode                    = "strict"
reportImportCycles                  = "information"
reportUnusedImport                  = "warning"
reportUnusedClass                   = "warning"
reportUnusedFunction                = "warning"
reportUnusedVariable                = "warning"
reportMissingTypeStubs              = "warning"
reportCallInDefaultInitializer      = "error"
reportImplicitStringConcatenation   = "error"
reportUnnecessaryTypeIgnoreComment  = "error"
```
