### ISSUE TITLE
`include` option does not work, Pyright still includes other folders

### ISSUE THREAD

**Issue by rafrafek** [microsoft/pyright#5695]
Hello,

I have the following entry in pyproject.toml:
```toml
[tool.pyright]
include = ["empty_folder/"]
```

and I run pyright@1.1.321 via pre-commit hook:
```yaml
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: node
        require_serial: true
        types: [python]
        additional_dependencies: ["pyright@1.1.321"]
```

using command `pre-commit run pyright -a`

The `empty_folder` is just an empty folder.

I expect Pyright to do nothing in this case. However, Pyright scans all my files in other folders in the root directory.

I've also tried with `include = []` with the same result.

How to force Pyright to scan only specified folders in my case?

Thanks!
