### ISSUE TITLE
Calling a callable `Annotated` type falsely triggers 'reportCallIssue' 

### ISSUE THREAD

**Issue by FynnBe** [microsoft/pyright#7370]
According to [typing.Annotated docs](https://docs.python.org/3/library/typing.html#typing.Annotated) 
> If a library or tool encounters an annotation Annotated[T, x] and has no special logic for the metadata, it should ignore the metadata and simply treat the annotation as T

I therefore would expect the below code snippet to pass without error, even with strict type checking.

```python
from typing import Annotated

A = Annotated[int, "whatever"]

A(5)
```
`5:1 - error: Object of type "type[Annotated]" is not callable (reportCallIssue)`

- python 3.12.1
- pyright 1.1.351

<details><summary>pyproject.toml section</summary>

```toml
[tool.pyright]
pythonPlatform = "All"
pythonVersion = "3.12"
reportIncompatibleMethodOverride = true
reportMissingSuperCall = "error"
reportMissingTypeArgument = true
reportMissingTypeStubs = "warning"
reportUninitializedInstanceVariable = "error"
reportUnknownMemberType = false
reportUnnecessaryIsInstance = false
reportUnnecessaryTypeIgnoreComment = "error"
reportUnusedCallResult = "error"
reportUnusedVariable = "error"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true
```

</details>
