### ISSUE TITLE
Different behavior between `pyrightconfig.json` and `pyproject.toml`

### ISSUE THREAD

**Issue by augustelalande** [microsoft/pyright#8102]
**Describe the bug**
Basically, everything works fine if I use `pyrightconfig.json`, and run `pyright` with no arguments
```json
{
    "ignore": [
        "test/*"
    ],
}
```
But If I do the same with I do the same with `pyproject.toml` the analysis takes much longer.
```toml
[tool.pyright]
ignore = ["test/*"]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
addopts = "--capture=no --cov-report html --cov-report json --cov=."

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = [
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
    "@(abc\\.)?abstractmethod",
]
```

**Code or Screenshots**
Running the command with verbose: `pyright --verbose` reveals something interesting
First with `pyrightconfig.json`, pyright auto-excludes `<project>\venv` and finds 68 source files.
```
Loading configuration file at <project>\pyrightconfig.json
Assuming Python version 3.11.9.final.0
No include entries specified; assuming <project>
Auto-excluding **/node_modules
Auto-excluding **/__pycache__
Auto-excluding **/.*
Search paths for file:///<project>
  c:\Users\Auguste\.cache\pyright-python\1.1.366\node_modules\pyright\dist\typeshed-fallback\stdlib
  <project>
  <project>\typings
  c:\Users\Auguste\.cache\pyright-python\1.1.366\node_modules\pyright\dist\typeshed-fallback\stubs\...
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311\DLLs
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311\Lib
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311
  <project>\venv
  <project>\venv\Lib\site-packages
  <project>\venv\Lib\site-packages\win32
  <project>\venv\Lib\site-packages\win32\lib
  <project>\venv\Lib\site-packages\pythonwin
Auto-excluding <project>\venv
Found 68 source files
...
...
...
```
But with `pyproject.toml`, pyright does not exclude venv and finds 4741.
```
Loading pyproject.toml file at <project>\pyproject.toml
Assuming Python version 3.11.9.final.0
Search paths for file:///<project>
  c:\Users\Auguste\.cache\pyright-python\1.1.366\node_modules\pyright\dist\typeshed-fallback\stdlib
  <project>
  <project>\typings
  c:\Users\Auguste\.cache\pyright-python\1.1.366\node_modules\pyright\dist\typeshed-fallback\stubs\...
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311\DLLs
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311\Lib
  c:\Users\Auguste\AppData\Local\Programs\Python\Python311
  <project>\venv
  <project>\venv\Lib\site-packages
  <project>\venv\Lib\site-packages\win32
  <project>\venv\Lib\site-packages\win32\lib
  <project>\venv\Lib\site-packages\pythonwin
Found 4741 source files
...
...
...
```

So the question is, why the different behavior?

**command-line**
`pyright`
