### ISSUE TITLE
To use wildcards in tool.pyright.executionEnvironments

### ISSUE THREAD

**Issue by sassanh** [microsoft/pyright#8108]
Firstly, thank you for maintaining Pyright. It is an incredibly helpful tool.

After version 1.1.366 I need to have these lines in my pyproject.toml to hint pyright each of these directories can import files inside their own directory:

```toml
[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/000-sound"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/010-notifications"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/010-voice"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/020-keyboard"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/020-keypad"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/030-ethernet"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/030-ip"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/030-wifi"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/040-camera"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/040-rgb-ring"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/040-sensors"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/050-lightdm"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/050-ssh"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/050-vscode"

[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/080-docker"
```

This is happening in this repository: https://github.com/ubopod/ubo_app/
These lines are not yet present in the repository because I haven't yet commit after 1.1.366.
Pyright automagically worked for my directory structure until version 1.1.365 without needing any extra config: https://github.com/ubopod/ubo_app/actions/runs/9114239601/job/25063658154#step:6:14

I wonder if we can support wildcards or regular expressions in the `root` property of the `executionEnvironments` items to avoid repeating config so that I could write the rest like this:

```toml
[[tool.pyright.executionEnvironments]]
root = "ubo_app/services/*"
```

I understand this may be a niche use-case and might have a lower priority.
