### ISSUE TITLE
Add type checking mode to execution environments

### ISSUE THREAD

**Issue by haarisr** [microsoft/pyright#8263]
If you have a question about a behavior that you’re seeing in pyright, consider posting to the [Pyright discussion forum](https://github.com/microsoft/pyright/discussions).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem.
Currently, the execution environments allow to override type check settings per environment specified. I would like to request to make this easier by just specifying a different mode for the directory.

This enables certain packages to be strictly typed and other's where it is currently not possible to be of the standard type checking mode.

**Describe the solution you’d like**
A clear and concise description of the solution you would like to see.

```toml
[tool.pyright]
include = ["src"]
typeCheckingMode = "standard"

executionEnvironments = [
    { root = "src/module_a", typeCheckingMode = "strict" },
    { root = "src/module_b", typeCheckingMode = "strict"},
]
```
