### ISSUE TITLE
pyright hangs after instaling matplotlib on my project

### ISSUE THREAD

**Issue by ttti07** [microsoft/pyright#8269]
**Describe the bug**
Before installing matplotlib on my project, pyright works very well.
However, after installing it, pyright started to hang;
`node` process of pyright takes about 1~2 CPU cores and few GBytes of memory, and it's getting higher as time goes by.
It's been a few minutes since it started, but it's not over.
I registered pyright as a pre-commit hook, so in my terminal it shows like below:
```sh
$ git commit
check for added large files..............................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
ruff.....................................................................Passed
ruff-format..............................................................Passed
pyright..................................................................
```

When I installed matplotlib, below dependencies are installed too.
```sh
$ pip install matplotlib
...
Successfully installed contourpy-1.2.1 cycler-0.12.1 fonttools-4.53.0 kiwisolver-1.4.5 matplotlib-3.9.0 pyparsing-3.1.2
```
I think this issue is similar to https://github.com/microsoft/pyright/issues/3206

**Code or Screenshots**
.

**VS Code extension or command-line**
I installed pyright==1.1.369, with .pre-commit-config.yaml like below
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        always_run: true
      - id: check-toml
        always_run: true
      - id: check-yaml
        args: [ --unsafe ]
        always_run: true
      - id: end-of-file-fixer
        always_run: true
      - id: trailing-whitespace
        always_run: true
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [ --fix ]
        always_run: true
      - id: ruff-format
        always_run: true
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        language_version: 16.17.1
        types: [ python ]
        verbose: true
        always_run: true
```
