### ISSUE TITLE
`reportPrivateImportUsage` false negatives when running `pyright <directory>` but not when running `find <directory> -name '*.py' | xargs pyright`

### ISSUE THREAD

**Issue by tamird** [microsoft/pyright#8377]
In my project I have
```
├── lib/common
│   ├── common
│   │   ├── py.typed
│   │   ├── db
│   │   │   ├── sites
│   │   │   │   ├── models.py # from common.db.sites.objects import WeatherState
│   │   │   │   ├── objects.py # class WeatherState: ...
│   ├── tests
│   │   ├── external_clients
│   │   │   ├── openweather
│   │   │   │   ├── test_openweather.py # from common.db.sites.models import WeatherState
│   ├── pyproject.toml
```

If I run `poetry run pyright lib/common` I get no diagnostics. If I run `find lib/common -name '*.py' | xargs -P24 -n1 poetry run pyright -p . --warnings` I get:
```
<path-to-repo>/lib/common/tests/external_clients/openweather/test_openweather.py                                                                  
  <path-to-repo>/lib/common/tests/external_clients/openweather/test_openweather.py:8:36 - error: "WeatherState" is not exported from module "common.db.sites.models"                                                                                                                                                         
    Import from "common.db.sites.objects" instead (reportPrivateImportUsage)

```

I'm using pyright 1.1.371:
```
poetry run pyright --version
pyright 1.1.371
```

**Comment by erictraut** [comment]
I'm having trouble reproing the problem. I suspect it's because I don't know anything about poetry. Could you create a simpler repro case that doesn't require poetry? Or does this repro for you only if you're using poetry. I think poetry may do odd things with the working directory. Also, it would be useful to see the relevant contents of your pyproject.toml file.

**Comment by tamird** [comment]
I'm not sure how I'd go about creating a simpler repro (the skeleton I wrote above is my attempt to do so).

I believe poetry is just activating the venv and running pyright. I can reproduce just the same:
```shell
tamird@Tamirs-MBP python_monorepo % . .venv/bin/activate        
(root-py3.12) tamird@Tamirs-MBP python_monorepo % .venv/bin/pyright lib/common
0 errors, 0 warnings, 0 informations 
(root-py3.12) tamird@Tamirs-MBP python_monorepo % .venv/bin/pyright lib/common/tests/external_clients/openweather/test_openweather.py
<pwd>/lib/common/tests/external_clients/openweather/test_openweather.py
  <pwd>/lib/common/tests/external_clients/openweather/test_openweather.py:8:36 - error: "WeatherState" is not exported from module "common.db.sites.models"
    Import from "common.db.sites.objects" instead (reportPrivateImportUsage)
1 error, 0 warnings, 0 informations 

```

Here's the (hopefully relevant) content of the `pyproject.toml` file:
```toml
[tool.pyright]
# TODO: Remove these when we have property subclasses instead of type aliases of `Annotated`.
reportArgumentType = false # Argument of type "ProfileClass" cannot be assigned to parameter "cast_to" of type "type[CastT@require_single]" in function "require_single"
reportCallIssue = false    # Object of type "type[Annotated]" is not callable

# TODO: Figure out why pyright thinks Supply_Property/SupplyPropertyMixin/Supply_TPR_Property are unhashable and remove.
reportUnhashable = false # Type "Supply_Property" is not hashable (reportUnhashable)
```
really not much going on here.
