### ISSUE TITLE
Disabling  `reportUnusedCallResult` for specific functions

### ISSUE THREAD

**Issue by jorenham** [microsoft/pyright#8650]
A very common use-case of `typing.assert_type` is in type tests, e.g. the [NumPy type tests](https://github.com/numpy/numpy/tree/v2.0.1/numpy/typing/tests/data/reveal) do this.

But currently when `reportUnusedCallResult` is enabled, the following code 

```python
from typing import Literal, assert_type

assert_type(0, Literal[0])
```

results in the following pyright error:

```
Result of call expression is of type "Literal[0]" and is not used; assign to variable "_" if this is intentional  (reportUnusedCallResult)
```

https://pyright-play.net/?strict=true&reportUnusedCallResult=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAySMApiAIYA2ANFOQM71kwD68CJAUJw03m4hIAKAAy0ipCpQDaIgLoBKTkA

This isn't only limited to `assert_type`; e.g. the return value of `dict.setdefault` is also often ignored, and I'm sure there are many more cases like these.

---

So I think that the cleanest solution would be to have a configuration option that disables `reportUnusedCallResult` for specific functions, which in a `pyproject.toml` could look like:

```toml
[tool.pyright]
# [...]
reportUnusedCallResult = true
ignoreUnusedCallResult = [
    "dict.setdefault", 
    "typing.assert_type", 
    "typing_extensions.assert_type"
]
# [...]
```
