### ISSUE TITLE
venv and venvPath not working with latest update (version 1.1.386)

### ISSUE THREAD

**Issue by the-citto** [microsoft/pyright#9335]
**Describe the bug**
`venv` and `venvPath` stopped working with version 1.1.386, rollback to 1.1.385 fixed.

**Code or Screenshots**
```toml
[tool.pyright]
venvPath = "."
venv = ".venv"
```

**Setup**
NeoVim LSP in WSL, using the virtual environment created with Windows' python i.e., .venv/Scripts/python.exe

this also means that activating the Windows' environment from Linux is not an option

**Additional details**
Using NeoVim in WSL but with developing for Windows, the settings working up to 1.1.385 were very convenient for my workflow

I also found suggestions in somehow related issues that `pythonPath` would be more appropriate to use than `venvPath` + `venv`

I tried `pythonPath`, both with relative and with absolute path, both with 1.1.385 and 1.1.386, but it didn't work with my setup 
```toml
[tool.pyright]
pythonPath = ".venv/Scripts/python.exe"
```
nor
```toml
[tool.pyright]
pythonPath = "/mnt/c/Users/<my-user>/<my-project-path>/.venv/Scripts/python.exe"
```

additionally, relative paths would be best, regularly using and sharing projects' templates
