### ISSUE TITLE
Expand venvPath

### ISSUE THREAD

**Issue by tekumara** [microsoft/pyright#941]
Expand `~` when encounted in `venvPath`, eg: 
```
{
    "include": [
        "awesome_app",
    ],
    "venvPath": "~/.virtualenvs",
    "venv": "awesome_app"
}
```

Currently neither `venvPath` or the `-v` command line option expand `~` when passed.
`~` will only be expanded when `pyright -v` is run from a shell, and not from a pre-commit hook as follows:

```
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        args: [-v, ~/.virtualenvs]
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ['pyright@1.1.55']
```

Instead the user home directory has to be hard-coded, which breaks when the pre-commit hook is used across multiple people, or when pyright runs in CI/CD.

**Comment by jakebailey** [comment]
Note that `~` is typically expanded by the shell. If you give a program `~` at the terminal, the program will never know that this happened as the shell has already done it before providing the path. It's a bit iffy if programs are supposed to do this sort of expansion themselves, but in a config file, maybe.

Another option would be to activate the environment before you run the hooks, if that works for your setup.

**Comment by jakebailey** [comment]
Though now that I think about it, setting `venvPath` and `venv` are a bit unusual if you're working with a regular repo; you're effectively overriding any configuration done automatically or done by the editor. I might be wrong, but this works for the original use case of pyright because that team has a pretty specific layout. If someone else clones the repo, you might start hitting trouble if people aren't using that same setup.

**Comment by erictraut** [comment]
The "~" character is a character that appears only in certain shells on some platforms. It should not appear in cross-platform config files. This is by design.

**Comment by tekumara** [comment]
I was using the hook recommend in [ci-integration.md](https://github.com/microsoft/pyright/blob/master/docs/ci-integration.md). So that needs to be a shell script instead that activates the virtualenv, so imports can be found. eg:

```yaml
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: ./.pre-commit-pyright.sh
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ['pyright@1.1.62']
```

.pre-commit-pyright.sh
```bash
#!/bin/bash

source ~/.virtualenvs/awesome_app/bin/activate
pyright
```
