### ISSUE TITLE
Pyproject file parse failures with no error message

### ISSUE THREAD

**Issue by garymm** [microsoft/pyright#9657]
```
➜ uv run --extra pyright pyright
Pyproject file parse attempt 1 error: {}
Pyproject file parse attempt 2 error: {}
Pyproject file parse attempt 3 error: {}
Pyproject file parse attempt 4 error: {}
Pyproject file parse attempt 5 error: {}
Pyproject file parse attempt 6 error: {}
Config file "/home/garymm/src/Astera-org/obelisk/research/pyproject.toml" could not be parsed. Verify that format is correct.
```

Here's the contents of the file:
```toml
#:schema https://json.schemastore.org/pyproject.json
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "research"
requires-python = ">=3.11,<3.12"
# https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#static-vs-dynamic-metadata
dynamic = ["version"]
dependencies = [
    "ale-py>=0.10.1",
    "craftax>=1.4.4",
    "draccus",
    "equinox>=0.11.10",
    "flashbax",
    "graphviz>=0.20.3",
    "gymnasium>=1.0.0",
    "gymnax",
    "jax>=0.4.33,<0.4.38",
    "jax_loop_utils[audio-video]",
    "jmp>=0.0.4",
    "loguru>=0.7.2",
    "mlflow-skinny>=2.16.2",
    "opencv-python-headless>=4.10.0.84",
    "optax>=0.2.3",
    "orbax-checkpoint>=0.10.2",
    "ott-jax>=0.4.8",
    "pytest-cov>=5.0.0",
    "pytest-skip-slow>=0.0.5",
    "pytest>=8.3.3",
    "rlax>=0.1.6",
    "tdqm>=0.0.1",
    "tensorboard>=2.18.0",
    "torch>=2.4.1",
    "xminigrid",
]

[project.optional-dependencies]
cuda = ["jax[cuda12]>=0.4.33"]
jupyter = ["ipykernel>=6.29.5,<6.30"]
pyright = ["pyright==1.1.391"]


[tool.ruff.lint]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "PT",  # flake8-pytest-style
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
]
ignore = [
    "A003",   # builtin-attribute-shadowing
    "SIM108", # Use the ternary operator
    "UP007",  # Allow Optional[type] instead of X | Y
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.pyright]
typeCheckingMode = "standard"

[tool.pytest.ini_options]
filterwarnings = [
    # Please only ignore warnings that come from a transitive dependency that we
    # can't easily avoid.
    # See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#controlling-warnings
    # action:message:category:module:line
    "error",
    # TODO: remove once these are merged:
    # https://github.com/instadeepai/flashbax/pull/43
    # https://github.com/instadeepai/flashbax/pull/45
    'ignore::UserWarning:flashbax.buffers.trajectory_buffer',
    'ignore::DeprecationWarning:pygame.pkgdata.*',
    'ignore:objective_name and minimize are deprecated:DeprecationWarning',
    "ignore:Deprecated call to `pkg_resources.declare_namespace\\('google'\\)`.*:DeprecationWarning",
    'ignore:.*pkg_resources.*:DeprecationWarning:mlflow.utils.requirements_utils',
    # TODO: Remove if https://github.com/MichaelTMatthews/Craftax/issues/31 is ever fixed.
    "ignore:Pickled array contains an aval with a named_shape attribute:DeprecationWarning",
    # https://github.com/google/jaxopt/issues/584
    "ignore:invalid escape sequence::.*jaxopt.*",
    # https://github.com/microsoft/debugpy/issues/1623
    "ignore::matplotlib._api.deprecation.MatplotlibDeprecationWarning:pydev",
]
addopts = "--strict-markers"
markers = ["slow"]

[tool.setuptools]
packages = ["research"]

[tool.uv]
# restrict to platforms we care about so that version resolution is faster and more likely to succeed
# (e.g. don't fail if a package isn't built for windows)
environments = [
    "sys_platform == 'darwin' and platform_machine == 'arm64' and python_version>='3.11' and python_version<'3.12'",
    "sys_platform == 'linux' and platform_machine == 'aarch64' and python_version>='3.11' and python_version<'3.12'",
    "sys_platform == 'linux' and platform_machine == 'x86_64' and python_version>='3.11' and python_version<'3.12'",
]
[tool.uv.sources]
flashbax = { git = "https://github.com/instadeepai/flashbax", rev = "a8ff66c8a66117e3f9e05fffc8679beaa77aa35e" }
xminigrid = { git = "https://github.com/corl-team/xland-minigrid", rev = "a46e78ce92f28bc90b8aac96d3b7b7792fb5bf3b" }
gymnax = { git = "https://github.com/Astera-org/gymnax", rev = "c52a7dac7b41514297d2e98b1b288d56715a5165" }
draccus = { git = "https://github.com/dlwh/draccus", rev = "f78f3527d6436d74fb12d17e32a17e85d433d222" }
jax_loop_utils = { git = "https://github.com/Astera-org/jax_loop_utils", rev = "e84187fab83d3409bd03ccfa738172952c9a9f6b" }
```
