### ISSUE TITLE
Inheritable pyright configuration

### ISSUE THREAD

**Issue by uwu-420** [microsoft/pyright#9787]
Hi, thanks for making pyright!

I'm trying out a monorepo setup which has a `pyproject.toml` file at the root level and one per sub-project in the monorepo. Ideally, I'd like to set some thing like
```toml
# ./pyproject.toml
[tool.pyright]
typeCheckingMode = "strict"
```
only once in the root-level `pyproject.toml` file and the sub-projects automatically inherit that setting unless overridden in their respective `pyproject.toml`. Another possibility would be to do it like ruff (see https://docs.astral.sh/ruff/settings/#extend). So something like this in the sub-project's `pyproject.toml`
```toml
# ./sub_project/pyproject.toml
[tool.pyright]
extend = "../pyproject.toml"
# Inherits typeCheckingMode = "strict"
ignore = ["foo.py"]
```
Cheers!
